# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required configuration version
version: 2

# Build settings
build:
  os: ubuntu-22.04  # Using a stable LTS version
  tools:
    python: "3.11"  # Your project's Python version

# Sphinx configuration
sphinx:
  configuration: source/conf.py  # Updated to your 'source' directory

# Documentation formats to build
formats:  # Remove 'html' and ensure correct indentation
  - pdf
  - epub

# Python dependencies
python:
  install:
    - requirements: requirements.txt  # Your 'requirements.txt' in the base directory
